main: TColor910.o TShape910.o TEllipse910.o Main910.o
	g++ TColor910.o TShape910.o TEllipse910.o Main910.o -o main
TColor910.o: TColor910.cpp
	g++ -c TColor910.cpp
TShape910.o: TShape910.cpp
	g++ -c TShape910.cpp
TEllipse910.o: TEllipse910.cpp
	g++ -c TEllipse910.cpp
Main910.o: Main910.cpp
	g++ -c Main910.cpp


